### ISSUE TITLE
Use LUKSO Web Components for styling

### ISSUE THREAD

**Issue by fhildeb** [lukso-network/tools-erc725-inspect#74]
### Request
ERC725 Tools should use LUKSO's web components to style all pages, aligning with the corporate design

### Current Behaviour
Regular Bulma styling + some component adjustments

**Comment by CJ42** [comment]
I think current design is ok. Bulma is easy to use. But a mixture of both could do

**Comment by fhildeb** [comment]
Indeed. The request was coming from Tim & Dominik, as we have pre-build style components for our other web pages that could easily be integrated.

**Comment by Hugoo** [comment]
This is low prio

**Comment by Hugoo** [comment]
We don't need that really, i will close.
